add safe_eq
prove-rs/z3.rs pull request #130
Opened 2021-03-05 20:22 UTC by rlkelly

this is adds a method "_safe_eq" that returns a `Result` when comparing two ast nodes and checks that they have the same `SortKind`.

2021-03-07 18:04 UTC, sameer requested changes

2021-03-07 18:04 UTC, sameer commented on z3/src/ast.rs
> +            Err(format!("Can not compare nodes, Sort does not match.  Nodes contain types {:?} and {:?}", left_sort, right_sort))
I agree that it's implied that the two don't have the same sort but I don't think the Err type should be a string. Maybe better suited as a struct whose display trait impl is the error message. Like

```rust
struct SortDiffers<'ctx> {
  left: Sort<'ctx>, right: Sort<'ctx>
}

impl<'ctx> Display for Sort<'ctx> { ... }
```

2021-03-07 18:04 UTC, sameer commented on z3/src/ast.rs
> +    fn _safe_eq(&self, other: &Self) -> Result<Bool<'ctx>, std::string::String> {
now that there's a safe method could you make `_eq` call it? That way z3 can unwrap with the error message instead of just the opaque assertion.

2021-03-08 22:37 UTC, rlkelly commented on z3/src/lib.rs
> +pub use z3_sys::{AstKind, GoalPrec, SortKind};
I just want to point this out, I hope this is alright.

2021-03-09 23:12 UTC, rlkelly commented
#129

2021-03-10 01:08 UTC, rlkelly commented on z3/src/ast.rs
> +                assert!(!func_decl.is_null(), "Ast has a null Z3_func_decl.");
it was a sanity check, we can get rid of it though

2021-03-10 19:45 UTC, rlkelly commented
I added three small changes.  I removed clone from tactic since this will raise reference count errors, made tactics take references, and made `list_subgoals` move the `ApplyResult`.

2021-03-10 22:11 UTC, sameer commented
Will review once I'm done with work but the changes sound reasonable 🙂

On Wed, Mar 10, 2021, at 17:10, Rob Kelly wrote:
> 

> this is ready for merge if the changes I made are acceptable


> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://github.com/prove-rs/z3.rs/pull/130#issuecomment-796207335>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ACUVICENZHYFUKW7PW6Q5CTTC7N3RANCNFSM4YV2VLDA>.

2021-03-11 01:13 UTC, sameer approved these changes
thanks for powering through these changes, looks great! :rocket:

2021-03-11 01:13 UTC, sameer commented on z3/src/tactic.rs
> -    fn clone(&self) -> Self {
I understand the point of the change and I'm fine with it, but in the future it would be better-suited to a separate PR

2021-03-11 01:15 UTC, merged