Add option to choose z3.h location for bindgen
prove-rs/z3.rs pull request #161
Opened 2021-09-16 16:35 UTC by futile

This enables the user to choose the path to their z3.h, and doesn't force usage of the system header through wrapper.h.

I.e., by setting the environment variable `Z3_SYS_Z3_HEADER`, the user can determine which z3.h will be used.

Needed this in a project where we definitely *did not* want to use the system z3.

2021-09-16 17:08 UTC, sameer requested changes
The use case makes sense to me, thanks for making this change! :rocket:

One minor thing: could we document it in the README for z3-sys? That way others can find the option.

2021-09-17 10:17 UTC, futile commented
> The use case makes sense to me, thanks for making this change! 
> 
> One minor thing: could we document it in the README for z3-sys? That way others can find the option.

Thanks for the feedback! I added a section to z3-sys/README.md, does that fit?

2021-09-17 15:01 UTC, sameer commented
Looks good to me :slightly_smiling_face:

2021-09-17 15:05 UTC, sameer approved these changes

2021-09-17 16:29 UTC, merged